apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  namespace: url-shortener
data:
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  DB_NAME: "urlshortener"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-svc:9092"
  ELASTICSEARCH_URIS: "http://opensearch-svc:9200"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  RATE_LIMIT_API: "10"
  RATE_LIMIT_REDIRECT: "60"
